07/30/2021 12:35:18 AM logging in using static token
07/30/2021 12:35:19 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:35:20 AM Shard ID None has connected to Gateway: ["gateway-prd-main-8357",{"micros":54845,"calls":["discord-sessions-green-prd-2-8",{"micros":54012,"calls":["start_session",{"micros":25575,"calls":["api-prd-main-9bxc",{"micros":22909,"calls":["get_user",{"micros":2434},"add_authorized_ip",{"micros":1285},"get_guilds",{"micros":3854},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":26071,"calls":[]}]}]}] (Session ID: 99e71ced626c8248a369d699344daa34).
07/30/2021 12:35:56 AM Received signal to terminate bot and event loop.
07/30/2021 12:35:56 AM Cleaning up tasks.
07/30/2021 12:35:56 AM Cleaning up after 2 tasks.
07/30/2021 12:35:56 AM All tasks finished cancelling.
07/30/2021 12:35:56 AM Closing the event loop.
07/30/2021 12:35:57 AM logging in using static token
07/30/2021 12:35:58 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:35:58 AM Shard ID None has connected to Gateway: ["gateway-prd-main-56hk",{"micros":54095,"calls":["discord-sessions-green-prd-2-166",{"micros":53107,"calls":["start_session",{"micros":32628,"calls":["api-prd-main-c3w7",{"micros":29891,"calls":["get_user",{"micros":3274},"add_authorized_ip",{"micros":1507},"get_guilds",{"micros":7836},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 490f29c01933bab9dc32c0dd55c0a196).
07/30/2021 12:36:00 AM Syncing commands...
07/30/2021 12:36:01 AM Syncing permissions...
07/30/2021 12:36:01 AM Deleting unused guild commands...
07/30/2021 12:36:02 AM Completed syncing all commands!
07/30/2021 12:37:14 AM Received signal to terminate bot and event loop.
07/30/2021 12:37:14 AM Cleaning up tasks.
07/30/2021 12:37:14 AM Cleaning up after 2 tasks.
07/30/2021 12:37:14 AM All tasks finished cancelling.
07/30/2021 12:37:14 AM Closing the event loop.
07/30/2021 12:37:16 AM logging in using static token
07/30/2021 12:37:17 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:37:17 AM Shard ID None has connected to Gateway: ["gateway-prd-main-46js",{"micros":53810,"calls":["discord-sessions-green-prd-2-42",{"micros":47173,"calls":["start_session",{"micros":37140,"calls":["api-prd-main-qd4g",{"micros":33479,"calls":["get_user",{"micros":6742},"add_authorized_ip",{"micros":1303},"get_guilds",{"micros":4286},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":0,"calls":[]}]}]}] (Session ID: e83cdaf042bc884eb995c5105a138701).
07/30/2021 12:37:19 AM Syncing commands...
07/30/2021 12:37:20 AM Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py:359> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn 0.options.0.description: Must be between 1 and 100 in length.')>
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 413, in sync_all_commands
    existing_cmds = await self.req.put_slash_commands(
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 0.options.0.description: Must be between 1 and 100 in length.
07/30/2021 12:37:57 AM Received signal to terminate bot and event loop.
07/30/2021 12:37:57 AM Cleaning up tasks.
07/30/2021 12:37:57 AM Cleaning up after 2 tasks.
07/30/2021 12:37:57 AM All tasks finished cancelling.
07/30/2021 12:37:57 AM Closing the event loop.
07/30/2021 12:37:59 AM logging in using static token
07/30/2021 12:38:00 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:38:00 AM Shard ID None has connected to Gateway: ["gateway-prd-main-rf43",{"micros":80356,"calls":["discord-sessions-green-prd-2-133",{"micros":79340,"calls":["start_session",{"micros":65984,"calls":["api-prd-main-l3tr",{"micros":55502,"calls":["get_user",{"micros":9307},"add_authorized_ip",{"micros":3220},"get_guilds",{"micros":4848},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1949,"calls":[]}]}]}] (Session ID: f8c82cd5d5b5b3b4d64438dc70ab8d86).
07/30/2021 12:38:03 AM Syncing commands...
07/30/2021 12:38:04 AM Task exception was never retrieved
future: <Task finished name='Task-1' coro=<SlashCommand.sync_all_commands() done, defined at D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py:359> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn 0.options.0.description: Must be between 1 and 100 in length.')>
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 413, in sync_all_commands
    existing_cmds = await self.req.put_slash_commands(
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 0.options.0.description: Must be between 1 and 100 in length.
07/30/2021 12:39:43 AM Received signal to terminate bot and event loop.
07/30/2021 12:39:43 AM Cleaning up tasks.
07/30/2021 12:39:43 AM Cleaning up after 2 tasks.
07/30/2021 12:39:43 AM All tasks finished cancelling.
07/30/2021 12:39:43 AM Closing the event loop.
07/30/2021 12:39:45 AM logging in using static token
07/30/2021 12:39:46 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:39:46 AM Shard ID None has connected to Gateway: ["gateway-prd-main-3518",{"micros":74994,"calls":["discord-sessions-green-prd-2-162",{"micros":73866,"calls":["start_session",{"micros":45930,"calls":["api-prd-main-mk7g",{"micros":42876,"calls":["get_user",{"micros":2384},"add_authorized_ip",{"micros":2671},"get_guilds",{"micros":13967},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 1c53cc9de999e6979e1fe35b104a5a18).
07/30/2021 12:39:48 AM Syncing commands...
07/30/2021 12:39:49 AM Syncing permissions...
07/30/2021 12:39:49 AM Deleting unused guild commands...
07/30/2021 12:39:50 AM Completed syncing all commands!
07/30/2021 12:40:06 AM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 26, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 30, in replyLinks
    result = self.analyzeCommand(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 113, in analyzeCommand
    if (ctx.prefix + ctx.invoked_with) == ctx.message.content:
AttributeError: 'SlashContext' object has no attribute 'prefix'
07/30/2021 12:43:11 AM Received signal to terminate bot and event loop.
07/30/2021 12:43:11 AM Cleaning up tasks.
07/30/2021 12:43:11 AM Cleaning up after 2 tasks.
07/30/2021 12:43:11 AM All tasks finished cancelling.
07/30/2021 12:43:11 AM Closing the event loop.
07/30/2021 12:43:14 AM logging in using static token
07/30/2021 12:43:15 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:43:15 AM Shard ID None has connected to Gateway: ["gateway-prd-main-5cp5",{"micros":126341,"calls":["discord-sessions-green-prd-2-40",{"micros":125003,"calls":["start_session",{"micros":111578,"calls":["api-prd-main-0qfb",{"micros":108066,"calls":["get_user",{"micros":16812},"add_authorized_ip",{"micros":9597},"get_guilds",{"micros":11648},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":3612,"calls":[]}]}]}] (Session ID: 901dff5a74519042ba7d7e71e9acab32).
07/30/2021 12:43:17 AM Syncing commands...
07/30/2021 12:43:18 AM Syncing permissions...
07/30/2021 12:43:18 AM Deleting unused guild commands...
07/30/2021 12:43:19 AM Completed syncing all commands!
07/30/2021 12:43:23 AM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 26, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
TypeError: replyLinks() missing 1 required positional argument: 'url'
07/30/2021 12:43:54 AM Received signal to terminate bot and event loop.
07/30/2021 12:43:54 AM Cleaning up tasks.
07/30/2021 12:43:54 AM Cleaning up after 2 tasks.
07/30/2021 12:43:54 AM All tasks finished cancelling.
07/30/2021 12:43:54 AM Closing the event loop.
07/30/2021 12:43:56 AM logging in using static token
07/30/2021 12:43:57 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:43:57 AM Shard ID None has connected to Gateway: ["gateway-prd-main-djhr",{"micros":45230,"calls":["discord-sessions-green-prd-2-107",{"micros":44144,"calls":["start_session",{"micros":32663,"calls":["api-prd-main-r0gt",{"micros":29809,"calls":["get_user",{"micros":3273},"add_authorized_ip",{"micros":1408},"get_guilds",{"micros":5153},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":12,"calls":[]},"presence_connect",{"micros":7219,"calls":[]}]}]}] (Session ID: a6dd6521355ecc44173d2f208b9278bc).
07/30/2021 12:43:59 AM Syncing commands...
07/30/2021 12:44:00 AM Syncing permissions...
07/30/2021 12:44:00 AM Deleting unused guild commands...
07/30/2021 12:44:01 AM Completed syncing all commands!
07/30/2021 12:44:48 AM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 65, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 92, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 374, in set_fields
    time.sleep(1)

07/30/2021 12:44:56 AM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 94, in replyLinks
    await ctx.edit(embed=embed, content=None)
AttributeError: 'SlashContext' object has no attribute 'edit'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce copy.py", line 104, in replyLinks
    await ctx.edit(content=e)
AttributeError: 'SlashContext' object has no attribute 'edit'
07/30/2021 12:44:56 AM Websocket closed with 1000, cannot reconnect.
07/30/2021 12:44:56 AM Attempting a reconnect in 0.73s
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 566, in connect
    await self.ws.poll_event()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\gateway.py", line 582, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
07/30/2021 12:44:58 AM Shard ID None has sent the RESUME payload.
07/30/2021 12:44:58 AM Shard ID None has successfully RESUMED session a6dd6521355ecc44173d2f208b9278bc under trace ["gateway-prd-main-ssrn",{"micros":566,"calls":["discord-sessions-green-prd-2-107",{"micros":36}]}].
07/30/2021 12:46:17 AM Received signal to terminate bot and event loop.
07/30/2021 12:46:17 AM Cleaning up tasks.
07/30/2021 12:46:17 AM Cleaning up after 2 tasks.
07/30/2021 12:46:17 AM All tasks finished cancelling.
07/30/2021 12:46:17 AM Closing the event loop.
07/30/2021 12:46:19 AM logging in using static token
07/30/2021 12:46:20 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 12:46:20 AM Shard ID None has connected to Gateway: ["gateway-prd-main-gr7l",{"micros":69530,"calls":["discord-sessions-green-prd-2-94",{"micros":68092,"calls":["start_session",{"micros":54451,"calls":["api-prd-main-gt4k",{"micros":51060,"calls":["get_user",{"micros":6066},"add_authorized_ip",{"micros":1207},"get_guilds",{"micros":3439},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 8f1eaa9d957acbe01a0f46bd012f4a11).
07/30/2021 12:46:22 AM Syncing commands...
07/30/2021 12:46:23 AM Syncing permissions...
07/30/2021 12:46:23 AM Deleting unused guild commands...
07/30/2021 12:46:24 AM Completed syncing all commands!
07/30/2021 01:39:14 AM Received signal to terminate bot and event loop.
07/30/2021 01:39:14 AM Cleaning up tasks.
07/30/2021 01:39:14 AM Cleaning up after 2 tasks.
07/30/2021 01:39:14 AM All tasks finished cancelling.
07/30/2021 01:39:14 AM Closing the event loop.
07/30/2021 01:56:00 AM logging in using static token
07/30/2021 01:56:01 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:56:02 AM Shard ID None has connected to Gateway: ["gateway-prd-main-zzkj",{"micros":94564,"calls":["discord-sessions-green-prd-2-49",{"micros":93217,"calls":["start_session",{"micros":73520,"calls":["api-prd-main-r93n",{"micros":65544,"calls":["get_user",{"micros":7836},"add_authorized_ip",{"micros":2387},"get_guilds",{"micros":17295},"coros_wait",{"micros":3}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":16077,"calls":[]}]}]}] (Session ID: 270d7dd4cb995bead15a5b27db9862ea).
07/30/2021 01:56:04 AM Syncing commands...
07/30/2021 01:56:05 AM Syncing permissions...
07/30/2021 01:56:05 AM Deleting unused guild commands...
07/30/2021 01:56:05 AM Completed syncing all commands!
07/30/2021 01:57:34 AM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 92, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 374, in set_fields
    time.sleep(1)

07/30/2021 01:57:42 AM Websocket closed with 1000, cannot reconnect.
07/30/2021 01:57:42 AM Attempting a reconnect in 0.33s
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 566, in connect
    await self.ws.poll_event()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\gateway.py", line 582, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
07/30/2021 01:57:43 AM Shard ID None has sent the RESUME payload.
07/30/2021 01:57:43 AM Shard ID None has successfully RESUMED session 270d7dd4cb995bead15a5b27db9862ea under trace ["gateway-prd-main-zmlr",{"micros":1114,"calls":["discord-sessions-green-prd-2-49",{"micros":41}]}].
07/30/2021 01:57:54 AM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 30, in replyLinks
    result = self.analyzeCommand(ctx, url)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 116, in analyzeCommand
    if re.search(r"https://(ptb\.|canary\.){0,1}discord(app){0,1}\.com/channels/\d+/\d+/\d+", ctx.message.content, re.I) != None:
AttributeError: 'NoneType' object has no attribute 'content'
07/30/2021 01:59:27 AM Received signal to terminate bot and event loop.
07/30/2021 01:59:27 AM Cleaning up tasks.
07/30/2021 01:59:27 AM Cleaning up after 2 tasks.
07/30/2021 01:59:27 AM All tasks finished cancelling.
07/30/2021 01:59:27 AM Closing the event loop.
07/30/2021 01:59:28 AM logging in using static token
07/30/2021 01:59:29 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:59:29 AM Shard ID None has connected to Gateway: ["gateway-prd-main-n8lp",{"micros":95950,"calls":["discord-sessions-green-prd-2-155",{"micros":94890,"calls":["start_session",{"micros":30404,"calls":["api-prd-main-mxsr",{"micros":27187,"calls":["get_user",{"micros":3071},"add_authorized_ip",{"micros":2791},"get_guilds",{"micros":3232},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":44388,"calls":[]}]}]}] (Session ID: 8a2073474077296bff2a083dec9d77f5).
07/30/2021 01:59:32 AM Syncing commands...
07/30/2021 01:59:33 AM Syncing permissions...
07/30/2021 01:59:33 AM Deleting unused guild commands...
07/30/2021 01:59:34 AM Completed syncing all commands!
07/30/2021 02:00:15 AM Received signal to terminate bot and event loop.
07/30/2021 02:00:15 AM Cleaning up tasks.
07/30/2021 02:00:15 AM Cleaning up after 3 tasks.
07/30/2021 02:00:15 AM All tasks finished cancelling.
07/30/2021 02:00:15 AM Closing the event loop.
07/30/2021 02:00:28 AM logging in using static token
07/30/2021 02:00:29 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:00:29 AM Shard ID None has connected to Gateway: ["gateway-prd-main-409b",{"micros":64503,"calls":["discord-sessions-green-prd-2-119",{"micros":62539,"calls":["start_session",{"micros":30006,"calls":["api-prd-main-7zkm",{"micros":22949,"calls":["get_user",{"micros":2350},"add_authorized_ip",{"micros":1395},"get_guilds",{"micros":3585},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":4745,"calls":[]}]}]}] (Session ID: 729452dd83c42edf96045efe6e39e865).
07/30/2021 02:00:31 AM Syncing commands...
07/30/2021 02:00:33 AM Syncing permissions...
07/30/2021 02:00:33 AM Deleting unused guild commands...
07/30/2021 02:00:33 AM Completed syncing all commands!
07/30/2021 02:01:20 AM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 91, in replyLinks
    await ctx.send(embed=embed, content=None)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 385, in set_fields
    embed.set_footer(text=embed.footer.text[:-51]+' | Searching...')
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 02:01:22 AM Received signal to terminate bot and event loop.
07/30/2021 02:01:22 AM Cleaning up tasks.
07/30/2021 02:01:22 AM Cleaning up after 2 tasks.
07/30/2021 02:01:22 AM All tasks finished cancelling.
07/30/2021 02:01:22 AM Closing the event loop.
07/30/2021 02:02:12 AM logging in using static token
07/30/2021 02:02:13 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:02:14 AM Shard ID None has connected to Gateway: ["gateway-prd-main-dgbm",{"micros":136863,"calls":["discord-sessions-green-prd-2-85",{"micros":132686,"calls":["start_session",{"micros":97323,"calls":["api-prd-main-fk45",{"micros":92195,"calls":["get_user",{"micros":7987},"add_authorized_ip",{"micros":7719},"get_guilds",{"micros":14812},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":28976,"calls":[]}]}]}] (Session ID: ae0a54a66b930bde04dd9484f1ae0a3a).
07/30/2021 02:02:16 AM Syncing commands...
07/30/2021 02:02:17 AM Syncing permissions...
07/30/2021 02:02:17 AM Deleting unused guild commands...
07/30/2021 02:02:18 AM Completed syncing all commands!
07/30/2021 02:02:44 AM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 38, in replyLinks
    ids = re.findall(r"\d+", ctx.message.content, re.I)
AttributeError: 'NoneType' object has no attribute 'content'
07/30/2021 02:03:23 AM Received signal to terminate bot and event loop.
07/30/2021 02:03:23 AM Cleaning up tasks.
07/30/2021 02:03:23 AM Cleaning up after 2 tasks.
07/30/2021 02:03:23 AM All tasks finished cancelling.
07/30/2021 02:03:23 AM Closing the event loop.
07/30/2021 02:03:24 AM logging in using static token
07/30/2021 02:03:25 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:03:26 AM Shard ID None has connected to Gateway: ["gateway-prd-main-njvj",{"micros":60093,"calls":["discord-sessions-green-prd-2-168",{"micros":59117,"calls":["start_session",{"micros":24076,"calls":["api-prd-main-s6xl",{"micros":21711,"calls":["get_user",{"micros":2251},"add_authorized_ip",{"micros":1860},"get_guilds",{"micros":3220},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":4644,"calls":[]}]}]}] (Session ID: 516759c089421c0257a75bbc801c731f).
07/30/2021 02:03:48 AM Received signal to terminate bot and event loop.
07/30/2021 02:03:48 AM Cleaning up tasks.
07/30/2021 02:03:48 AM Cleaning up after 5 tasks.
07/30/2021 02:03:48 AM All tasks finished cancelling.
07/30/2021 02:03:48 AM Closing the event loop.
07/30/2021 02:03:59 AM logging in using static token
07/30/2021 02:04:00 AM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:04:00 AM Shard ID None has connected to Gateway: ["gateway-prd-main-xhvr",{"micros":53018,"calls":["discord-sessions-green-prd-2-138",{"micros":51862,"calls":["start_session",{"micros":28386,"calls":["api-prd-main-h04z",{"micros":25291,"calls":["get_user",{"micros":2541},"add_authorized_ip",{"micros":1377},"get_guilds",{"micros":3528},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":8722,"calls":[]}]}]}] (Session ID: 8b4828c5c80700ea7cdb1933471e0fc5).
07/30/2021 02:04:02 AM Syncing commands...
07/30/2021 02:04:04 AM Syncing permissions...
07/30/2021 02:04:04 AM Deleting unused guild commands...
07/30/2021 02:04:04 AM Completed syncing all commands!
07/30/2021 02:05:34 AM Received signal to terminate bot and event loop.
07/30/2021 02:05:34 AM Cleaning up tasks.
07/30/2021 02:05:34 AM Cleaning up after 2 tasks.
07/30/2021 02:05:34 AM All tasks finished cancelling.
07/30/2021 02:05:34 AM Closing the event loop.
07/30/2021 01:11:06 PM logging in using static token
07/30/2021 01:11:07 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:11:08 PM Shard ID None has connected to Gateway: ["gateway-prd-main-2dq5",{"micros":64433,"calls":["discord-sessions-green-prd-2-36",{"micros":63649,"calls":["start_session",{"micros":34228,"calls":["api-prd-main-0dhm",{"micros":31330,"calls":["get_user",{"micros":3387},"add_authorized_ip",{"micros":2457},"get_guilds",{"micros":5935},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":26385,"calls":[]}]}]}] (Session ID: 0aaf41f87fbdf7a4a96c05b4d1f04782).
07/30/2021 01:11:10 PM Syncing commands...
07/30/2021 01:11:11 PM Syncing permissions...
07/30/2021 01:11:11 PM Deleting unused guild commands...
07/30/2021 01:11:12 PM Completed syncing all commands!
07/30/2021 01:23:57 PM Received signal to terminate bot and event loop.
07/30/2021 01:23:57 PM Cleaning up tasks.
07/30/2021 01:23:57 PM Cleaning up after 2 tasks.
07/30/2021 01:23:57 PM All tasks finished cancelling.
07/30/2021 01:23:57 PM Closing the event loop.
07/30/2021 01:24:00 PM logging in using static token
07/30/2021 01:24:01 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:24:01 PM Shard ID None has connected to Gateway: ["gateway-prd-main-gmc4",{"micros":52373,"calls":["discord-sessions-green-prd-2-57",{"micros":51586,"calls":["start_session",{"micros":24470,"calls":["api-prd-main-n2cx",{"micros":21686,"calls":["get_user",{"micros":2044},"add_authorized_ip",{"micros":1255},"get_guilds",{"micros":3041},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":17664,"calls":[]}]}]}] (Session ID: 72ac907d0e3376f394b703856039138c).
07/30/2021 01:24:03 PM Syncing commands...
07/30/2021 01:24:05 PM Syncing permissions...
07/30/2021 01:24:05 PM Deleting unused guild commands...
07/30/2021 01:24:05 PM Completed syncing all commands!
07/30/2021 01:24:08 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:24:08 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 391, in set_fields
    futures.append(await loop.create_task(excs[i], u))
NameError: name 'futures' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type NameError is not JSON serializable
07/30/2021 01:24:47 PM Received signal to terminate bot and event loop.
07/30/2021 01:24:47 PM Cleaning up tasks.
07/30/2021 01:24:47 PM Cleaning up after 2 tasks.
07/30/2021 01:24:47 PM All tasks finished cancelling.
07/30/2021 01:24:47 PM Closing the event loop.
07/30/2021 01:24:51 PM logging in using static token
07/30/2021 01:24:53 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:24:54 PM Shard ID None has connected to Gateway: ["gateway-prd-main-js98",{"micros":65728,"calls":["discord-sessions-green-prd-2-122",{"micros":64890,"calls":["start_session",{"micros":33545,"calls":["api-prd-main-kpng",{"micros":29745,"calls":["get_user",{"micros":3526},"add_authorized_ip",{"micros":1212},"get_guilds",{"micros":6794},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: f13d308d8fad926944070a00162ee8b4).
07/30/2021 01:24:56 PM Syncing commands...
07/30/2021 01:24:57 PM Syncing permissions...
07/30/2021 01:24:57 PM Deleting unused guild commands...
07/30/2021 01:24:58 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:24:58 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 392, in set_fields
    futures.append(await loop.create_task(excs[i], u))
TypeError: create_task() takes 2 positional arguments but 3 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:24:58 PM Completed syncing all commands!
07/30/2021 01:25:30 PM Received signal to terminate bot and event loop.
07/30/2021 01:25:30 PM Cleaning up tasks.
07/30/2021 01:25:30 PM Cleaning up after 2 tasks.
07/30/2021 01:25:30 PM All tasks finished cancelling.
07/30/2021 01:25:30 PM Closing the event loop.
07/30/2021 01:25:34 PM logging in using static token
07/30/2021 01:25:34 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:25:35 PM Shard ID None has connected to Gateway: ["gateway-prd-main-5c70",{"micros":39512,"calls":["discord-sessions-green-prd-2-169",{"micros":38045,"calls":["start_session",{"micros":28700,"calls":["api-prd-main-r85t",{"micros":25676,"calls":["get_user",{"micros":2279},"add_authorized_ip",{"micros":2242},"get_guilds",{"micros":4272},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":4412,"calls":[]}]}]}] (Session ID: dd2a2908b0033fa1b2da7c1e2b96483f).
07/30/2021 01:25:37 PM Syncing commands...
07/30/2021 01:25:38 PM Syncing permissions...
07/30/2021 01:25:38 PM Deleting unused guild commands...
07/30/2021 01:25:39 PM Completed syncing all commands!
07/30/2021 01:25:47 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:25:47 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 392, in set_fields
    futures.append(await loop.create_task(excs[i](u)))
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got ('saucenao', '[All Results](https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F763759441672798228%2F764297297940185110%2FWitch_Frey.png)\nLow similarity results.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:28:13 PM Received signal to terminate bot and event loop.
07/30/2021 01:28:13 PM Cleaning up tasks.
07/30/2021 01:28:13 PM Cleaning up after 2 tasks.
07/30/2021 01:28:13 PM All tasks finished cancelling.
07/30/2021 01:28:13 PM Closing the event loop.
07/30/2021 01:28:16 PM logging in using static token
07/30/2021 01:28:17 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:28:18 PM Shard ID None has connected to Gateway: ["gateway-prd-main-g2b5",{"micros":75627,"calls":["discord-sessions-green-prd-2-89",{"micros":74784,"calls":["start_session",{"micros":25175,"calls":["api-prd-main-7tfj",{"micros":22169,"calls":["get_user",{"micros":2489},"add_authorized_ip",{"micros":1459},"get_guilds",{"micros":2891},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 980d10daf845e4059d0b3c6b466547fb).
07/30/2021 01:28:20 PM Syncing commands...
07/30/2021 01:28:21 PM Syncing permissions...
07/30/2021 01:28:21 PM Deleting unused guild commands...
07/30/2021 01:28:21 PM Completed syncing all commands!
07/30/2021 01:28:33 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:28:33 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 392, in set_fields
    futures.append(await loop.create_task(excs[i](u)))
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got ['saucenao', '[All Results](https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F763759441672798228%2F764297297940185110%2FWitch_Frey.png)\nLow similarity results.']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:28:33 PM Websocket closed with 1006, attempting a reconnect.
07/30/2021 01:28:33 PM Got a request to RESUME the websocket.
07/30/2021 01:28:33 PM Attempting a reconnect in 1.08s
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 563, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 494, in wait_for
    return fut.result()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 967, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] The specified network name is no longer available
07/30/2021 01:28:35 PM Attempting a reconnect in 1.82s
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 563, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 494, in wait_for
    return fut.result()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 967, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\client.py", line 544, in _request
    await resp.start(conn)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\aiohttp\streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 64] The specified network name is no longer available
07/30/2021 01:28:37 PM Shard ID None has sent the RESUME payload.
07/30/2021 01:28:37 PM Shard ID None has successfully RESUMED session 980d10daf845e4059d0b3c6b466547fb under trace ["gateway-prd-main-x9p8",{"micros":727,"calls":["discord-sessions-green-prd-2-89",{"micros":18}]}].
07/30/2021 01:30:25 PM Received signal to terminate bot and event loop.
07/30/2021 01:30:25 PM Cleaning up tasks.
07/30/2021 01:30:25 PM Cleaning up after 2 tasks.
07/30/2021 01:30:25 PM All tasks finished cancelling.
07/30/2021 01:30:25 PM Closing the event loop.
07/30/2021 01:30:28 PM logging in using static token
07/30/2021 01:30:29 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:30:29 PM Shard ID None has connected to Gateway: ["gateway-prd-main-lpz7",{"micros":61734,"calls":["discord-sessions-green-prd-2-65",{"micros":60985,"calls":["start_session",{"micros":32362,"calls":["api-prd-main-3vkv",{"micros":29073,"calls":["get_user",{"micros":3120},"add_authorized_ip",{"micros":1318},"get_guilds",{"micros":2831},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":11576,"calls":[]}]}]}] (Session ID: fd4676c04c1ff4d29c93d181c8709f6c).
07/30/2021 01:30:32 PM Syncing commands...
07/30/2021 01:30:33 PM Syncing permissions...
07/30/2021 01:30:33 PM Deleting unused guild commands...
07/30/2021 01:30:46 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:30:46 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 393, in set_fields
    futures.append(await loop.create_task(excs[i](u)))
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got ('saucenao', '[All Results](https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F763759441672798228%2F764297297940185110%2FWitch_Frey.png)\nLow similarity results.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:30:46 PM Completed syncing all commands!
07/30/2021 01:31:15 PM Received signal to terminate bot and event loop.
07/30/2021 01:31:15 PM Cleaning up tasks.
07/30/2021 01:31:15 PM Cleaning up after 2 tasks.
07/30/2021 01:31:15 PM All tasks finished cancelling.
07/30/2021 01:31:15 PM Closing the event loop.
07/30/2021 01:35:53 PM logging in using static token
07/30/2021 01:35:54 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:35:54 PM Shard ID None has connected to Gateway: ["gateway-prd-main-zl23",{"micros":97943,"calls":["discord-sessions-green-prd-2-73",{"micros":96808,"calls":["start_session",{"micros":25394,"calls":["api-prd-main-j4pw",{"micros":22364,"calls":["get_user",{"micros":1976},"add_authorized_ip",{"micros":1305},"get_guilds",{"micros":2829},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":25667,"calls":[]}]}]}] (Session ID: 22a97b75044076060f24937996633408).
07/30/2021 01:35:56 PM Syncing commands...
07/30/2021 01:36:10 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:36:10 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 390, in set_fields
    add_field_(engine_)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 383, in add_field_
    if result[0] == engine.lower():
TypeError: '_asyncio.Future' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:36:10 PM Syncing permissions...
07/30/2021 01:36:10 PM Deleting unused guild commands...
07/30/2021 01:36:10 PM Completed syncing all commands!
07/30/2021 01:37:50 PM Received signal to terminate bot and event loop.
07/30/2021 01:37:50 PM Cleaning up tasks.
07/30/2021 01:37:50 PM Cleaning up after 2 tasks.
07/30/2021 01:37:50 PM All tasks finished cancelling.
07/30/2021 01:37:50 PM Closing the event loop.
07/30/2021 01:37:53 PM logging in using static token
07/30/2021 01:37:54 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:37:54 PM Shard ID None has connected to Gateway: ["gateway-prd-main-z9hg",{"micros":71499,"calls":["discord-sessions-green-prd-2-121",{"micros":70750,"calls":["start_session",{"micros":33907,"calls":["api-prd-main-q695",{"micros":30969,"calls":["get_user",{"micros":2201},"add_authorized_ip",{"micros":1455},"get_guilds",{"micros":3765},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: afe78a43c076bd463fe40f7a9f550d82).
07/30/2021 01:37:57 PM Syncing commands...
07/30/2021 01:38:45 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 390, in set_fields
    time.sleep(1)

07/30/2021 01:38:55 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 390, in set_fields
    time.sleep(1)

07/30/2021 01:38:56 PM Received signal to terminate bot and event loop.
07/30/2021 01:38:56 PM Cleaning up tasks.
07/30/2021 01:38:56 PM Cleaning up after 3 tasks.
07/30/2021 01:38:56 PM All tasks finished cancelling.
07/30/2021 01:38:56 PM Closing the event loop.
07/30/2021 01:38:56 PM _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_socket_response coro=<bound method SlashCommand.on_socket_response of <discord_slash.client.SlashCommand object at 0x000001CA57F9A3D0>> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 390, in set_fields
    time.sleep(1)
KeyboardInterrupt
07/30/2021 01:39:35 PM logging in using static token
07/30/2021 01:39:36 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:39:36 PM Shard ID None has connected to Gateway: ["gateway-prd-main-cnvm",{"micros":175988,"calls":["discord-sessions-green-prd-2-90",{"micros":175209,"calls":["start_session",{"micros":139526,"calls":["api-prd-main-b99d",{"micros":83514,"calls":["get_user",{"micros":19069},"add_authorized_ip",{"micros":7350},"get_guilds",{"micros":5093},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":8903,"calls":[]}]}]}] (Session ID: e7771dce7e1ad7888a758f64126922c6).
07/30/2021 01:39:38 PM Syncing commands...
07/30/2021 01:39:40 PM Syncing permissions...
07/30/2021 01:39:40 PM Deleting unused guild commands...
07/30/2021 01:39:40 PM Completed syncing all commands!
07/30/2021 01:46:53 PM Received signal to terminate bot and event loop.
07/30/2021 01:46:53 PM Cleaning up tasks.
07/30/2021 01:46:53 PM Cleaning up after 2 tasks.
07/30/2021 01:46:53 PM All tasks finished cancelling.
07/30/2021 01:46:53 PM Closing the event loop.
07/30/2021 01:46:57 PM logging in using static token
07/30/2021 01:46:58 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:46:58 PM Shard ID None has connected to Gateway: ["gateway-prd-main-cs38",{"micros":86270,"calls":["discord-sessions-green-prd-2-146",{"micros":85240,"calls":["start_session",{"micros":24519,"calls":["api-prd-main-5h5w",{"micros":21811,"calls":["get_user",{"micros":3062},"add_authorized_ip",{"micros":1297},"get_guilds",{"micros":2986},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":36888,"calls":[]}]}]}] (Session ID: 5afccbb74161f07667c85e53b16094a6).
07/30/2021 01:47:00 PM Syncing commands...
07/30/2021 01:47:14 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:47:14 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 379, in set_fields
    results.append(asyncio.create_task(excs[i](u)))
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 382, in create_task
    task = loop.create_task(coro)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got ('saucenao', "[All Results](https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F763759703816798218%2F764350518986014720%2F76091500_p0_master1200.jpg)\n__First Result__\nking's raid Mirianne\nPixiv ID: [76091500](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76091500)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:47:15 PM Syncing permissions...
07/30/2021 01:47:15 PM Deleting unused guild commands...
07/30/2021 01:47:16 PM Completed syncing all commands!
07/30/2021 01:49:00 PM Received signal to terminate bot and event loop.
07/30/2021 01:49:00 PM Cleaning up tasks.
07/30/2021 01:49:00 PM Cleaning up after 2 tasks.
07/30/2021 01:49:00 PM All tasks finished cancelling.
07/30/2021 01:49:00 PM Closing the event loop.
07/30/2021 01:49:03 PM logging in using static token
07/30/2021 01:49:04 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:49:05 PM Shard ID None has connected to Gateway: ["gateway-prd-main-vcl5",{"micros":65163,"calls":["discord-sessions-green-prd-2-82",{"micros":64186,"calls":["start_session",{"micros":29157,"calls":["api-prd-main-pkph",{"micros":26044,"calls":["get_user",{"micros":3272},"add_authorized_ip",{"micros":1861},"get_guilds",{"micros":3927},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 89f7462b9dbbe57035c36485ad1124c9).
07/30/2021 01:49:07 PM Syncing commands...
07/30/2021 01:49:08 PM Syncing permissions...
07/30/2021 01:49:08 PM Deleting unused guild commands...
07/30/2021 01:49:17 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 01:49:17 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 379, in set_fields
    results.append(await asyncio.create_task(excs[i](u)))
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\tasks.py", line 382, in create_task
    task = loop.create_task(coro)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 431, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got ('saucenao', "[All Results](https://saucenao.com/search.php?url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F763759703816798218%2F764350518986014720%2F76091500_p0_master1200.jpg)\n__First Result__\nking's raid Mirianne\nPixiv ID: [76091500](https://www.pixiv.net/member_illust.php?mode=medium&illust_id=76091500)")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TypeError is not JSON serializable
07/30/2021 01:49:17 PM Completed syncing all commands!
07/30/2021 01:49:39 PM Received signal to terminate bot and event loop.
07/30/2021 01:49:39 PM Cleaning up tasks.
07/30/2021 01:49:39 PM Cleaning up after 2 tasks.
07/30/2021 01:49:39 PM All tasks finished cancelling.
07/30/2021 01:49:39 PM Closing the event loop.
07/30/2021 01:56:11 PM logging in using static token
07/30/2021 01:56:12 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:56:12 PM Shard ID None has connected to Gateway: ["gateway-prd-main-3v0w",{"micros":142203,"calls":["discord-sessions-green-prd-2-87",{"micros":141348,"calls":["start_session",{"micros":67652,"calls":["api-prd-main-7z4v",{"micros":64660,"calls":["get_user",{"micros":6516},"add_authorized_ip",{"micros":3664},"get_guilds",{"micros":11883},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":67336,"calls":[]}]}]}] (Session ID: 2c5c0666a571b132778956a48335982e).
07/30/2021 01:56:14 PM Syncing commands...
07/30/2021 01:56:16 PM Syncing permissions...
07/30/2021 01:56:16 PM Deleting unused guild commands...
07/30/2021 01:57:03 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 390, in set_fields
    engine_list = ['SauceNAO', 'Yandex', 'IQDB', 'TinEye', 'Google']
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 01:57:13 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 390, in set_fields
    engine_list = ['SauceNAO', 'Yandex', 'IQDB', 'TinEye', 'Google']
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 01:57:17 PM Received signal to terminate bot and event loop.
07/30/2021 01:57:17 PM Cleaning up tasks.
07/30/2021 01:57:17 PM Cleaning up after 3 tasks.
07/30/2021 01:57:17 PM All tasks finished cancelling.
07/30/2021 01:57:17 PM Closing the event loop.
07/30/2021 01:57:45 PM logging in using static token
07/30/2021 01:57:45 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:57:46 PM Shard ID None has connected to Gateway: ["gateway-prd-main-drcs",{"micros":136686,"calls":["discord-sessions-green-prd-2-161",{"micros":135763,"calls":["start_session",{"micros":84757,"calls":["api-prd-main-6mr2",{"micros":81638,"calls":["get_user",{"micros":11944},"add_authorized_ip",{"micros":6628},"get_guilds",{"micros":20129},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":39020,"calls":[]}]}]}] (Session ID: 14d4d70649df383baa8c09bf13755df2).
07/30/2021 01:57:48 PM Syncing commands...
07/30/2021 01:57:50 PM Syncing permissions...
07/30/2021 01:57:50 PM Deleting unused guild commands...
07/30/2021 01:57:50 PM Completed syncing all commands!
07/30/2021 01:59:18 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 01:59:28 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 426, in set_fields
    add_field_(engine_)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 01:59:38 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 426, in set_fields
    add_field_(engine_)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 01:59:47 PM logging in using static token
07/30/2021 01:59:48 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 01:59:49 PM Shard ID None has connected to Gateway: ["gateway-prd-main-5cp5",{"micros":97949,"calls":["discord-sessions-green-prd-2-132",{"micros":97086,"calls":["start_session",{"micros":25996,"calls":["api-prd-main-0rq1",{"micros":23258,"calls":["get_user",{"micros":2177},"add_authorized_ip",{"micros":1093},"get_guilds",{"micros":3035},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":26471,"calls":[]}]}]}] (Session ID: 9de89acacc16a2a2dce00cf01f543df1).
07/30/2021 01:59:51 PM Syncing commands...
07/30/2021 01:59:52 PM Syncing permissions...
07/30/2021 01:59:52 PM Deleting unused guild commands...
07/30/2021 01:59:53 PM Completed syncing all commands!
07/30/2021 02:01:21 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:01:31 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:01:41 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:01:51 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:02:01 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:02:11 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:02:21 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:02:31 PM Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:02:32 PM Timed out receiving packet. Attempting a reconnect.
07/30/2021 02:02:32 PM Got a request to RESUME the websocket.
07/30/2021 02:02:33 PM Shard ID None has sent the RESUME payload.
07/30/2021 02:02:33 PM Shard ID None session has been invalidated.
07/30/2021 02:02:33 PM Got a request to IDENTIFY the websocket.
07/30/2021 02:02:39 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:02:40 PM Shard ID None has connected to Gateway: ["gateway-prd-main-6mgz",{"micros":658448,"calls":["discord-sessions-green-prd-2-81",{"micros":655691,"calls":["start_session",{"micros":612514,"calls":["api-prd-main-4pdk",{"micros":607806,"calls":["get_user",{"micros":14034},"add_authorized_ip",{"micros":1146},"get_guilds",{"micros":12616},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":5822,"calls":[]}]}]}] (Session ID: c91c0de15e9a4c72824eca4bb8088f57).
07/30/2021 02:04:39 PM Received signal to terminate bot and event loop.
07/30/2021 02:04:39 PM Cleaning up tasks.
07/30/2021 02:04:39 PM Cleaning up after 2 tasks.
07/30/2021 02:04:39 PM All tasks finished cancelling.
07/30/2021 02:04:39 PM Closing the event loop.
07/30/2021 02:04:46 PM logging in using static token
07/30/2021 02:04:47 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:04:47 PM Shard ID None has connected to Gateway: ["gateway-prd-main-d28m",{"micros":48932,"calls":["discord-sessions-green-prd-2-25",{"micros":48068,"calls":["start_session",{"micros":24986,"calls":["api-prd-main-rbfw",{"micros":21747,"calls":["get_user",{"micros":2169},"add_authorized_ip",{"micros":1263},"get_guilds",{"micros":3854},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 1381e982bd67778a77839b7f799424db).
07/30/2021 02:04:49 PM Syncing commands...
07/30/2021 02:04:51 PM Syncing permissions...
07/30/2021 02:04:51 PM Deleting unused guild commands...
07/30/2021 02:04:51 PM Completed syncing all commands!
07/30/2021 02:05:39 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 386, in set_fields
    if future._state == 'FINISHED':

07/30/2021 02:05:49 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 386, in set_fields
    if future._state == 'FINISHED':

07/30/2021 02:05:59 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 385, in set_fields
    for future in futures:

07/30/2021 02:06:09 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 386, in set_fields
    if future._state == 'FINISHED':

07/30/2021 02:06:20 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 386, in set_fields
    if future._state == 'FINISHED':

07/30/2021 02:06:30 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 385, in set_fields
    for future in futures:

07/30/2021 02:06:40 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 385, in set_fields
    for future in futures:

07/30/2021 02:06:50 PM Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 386, in set_fields
    if future._state == 'FINISHED':

07/30/2021 02:07:00 PM Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 386, in set_fields
    if future._state == 'FINISHED':

07/30/2021 02:07:07 PM Received signal to terminate bot and event loop.
07/30/2021 02:07:07 PM Cleaning up tasks.
07/30/2021 02:07:07 PM Cleaning up after 3 tasks.
07/30/2021 02:07:07 PM All tasks finished cancelling.
07/30/2021 02:07:07 PM Closing the event loop.
07/30/2021 02:07:07 PM _ClientEventTask exception was never retrieved
future: <ClientEventTask state=finished event=on_socket_response coro=<bound method SlashCommand.on_socket_response of <discord_slash.client.SlashCommand object at 0x0000029452DDA460>> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1231, in on_socket_response
    return await self._on_slash(to_use)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1292, in _on_slash
    await self.invoke_command(selected_cmd, ctx, args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 382, in set_fields
    if futures == []:
KeyboardInterrupt
07/30/2021 02:07:11 PM logging in using static token
07/30/2021 02:07:12 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:07:12 PM Shard ID None has connected to Gateway: ["gateway-prd-main-382p",{"micros":138880,"calls":["discord-sessions-green-prd-2-147",{"micros":138177,"calls":["start_session",{"micros":28196,"calls":["api-prd-main-kv0q",{"micros":25298,"calls":["get_user",{"micros":3141},"add_authorized_ip",{"micros":1420},"get_guilds",{"micros":3239},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":20595,"calls":[]}]}]}] (Session ID: f051310a9cb92f78f7c51b3ee91611dc).
07/30/2021 02:07:14 PM Syncing commands...
07/30/2021 02:07:16 PM Syncing permissions...
07/30/2021 02:07:16 PM Deleting unused guild commands...
07/30/2021 02:07:16 PM Completed syncing all commands!
07/30/2021 02:08:03 PM Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:08:13 PM Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:08:23 PM Shard ID None heartbeat blocked for more than 30 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:08:33 PM Shard ID None heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:08:43 PM Shard ID None heartbeat blocked for more than 50 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:08:53 PM Shard ID None heartbeat blocked for more than 60 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:09:03 PM Shard ID None heartbeat blocked for more than 70 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:09:13 PM Shard ID None heartbeat blocked for more than 80 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:09:23 PM Shard ID None heartbeat blocked for more than 90 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:09:33 PM Shard ID None heartbeat blocked for more than 100 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 416, in set_fields
    time.sleep(1)

07/30/2021 02:09:43 PM Shard ID None heartbeat blocked for more than 110 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 426, in set_fields
    add_field_(engine_)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 02:09:53 PM Shard ID None heartbeat blocked for more than 120 seconds.
Loop thread traceback (most recent call last):
  File "main.py", line 63, in <module>
    client.run(config.token, reconnect=True, bot=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 713, in run
    loop.run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 979, in on_message
    await self.process_commands(message)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 976, in process_commands
    await self.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 16, in sauce
    await self.replyLinks(ctx, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 131, in replyLinks
    embed = self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce.py", line 426, in set_fields
    add_field_(engine_)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\_base.py", line 644, in __exit__
    self.shutdown(wait=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\concurrent\futures\thread.py", line 236, in shutdown
    t.join()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):

07/30/2021 02:10:20 PM logging in using static token
07/30/2021 02:10:20 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:10:21 PM Shard ID None has connected to Gateway: ["gateway-prd-main-pzjs",{"micros":57942,"calls":["discord-sessions-green-prd-2-14",{"micros":57063,"calls":["start_session",{"micros":44145,"calls":["api-prd-main-scc2",{"micros":37911,"calls":["get_user",{"micros":4206},"add_authorized_ip",{"micros":1445},"get_guilds",{"micros":3721},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":3,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 2a821659fb49128fef1625d0e0161e55).
07/30/2021 02:10:23 PM Syncing commands...
07/30/2021 02:10:24 PM Syncing permissions...
07/30/2021 02:10:24 PM Deleting unused guild commands...
07/30/2021 02:10:25 PM Completed syncing all commands!
07/30/2021 02:10:53 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 29, in replyLinks
    await ctx.defer()
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 129, in defer
    await self._http.post_initial_response(base, self.interaction_id, self._token)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 250, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
07/30/2021 02:11:29 PM Deferred response might not be what you set it to! (hidden / visible) This is because it was deferred in a different state.
07/30/2021 02:11:29 PM An exception has occurred while executing command `sauce`:
Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 89, in replyLinks
    embed = await self.set_fields(embed, u, saucenao, google, yandex, tineye, iqdb, no_preview)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 387, in set_fields
    if future._state == 'FINISHED':
AttributeError: 'tuple' object has no attribute '_state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\client.py", line 1185, in invoke_command
    await func.invoke(ctx, **args)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\model.py", line 208, in invoke
    return await self.func(self.cog, *args, **kwargs)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 26, in sauce
    await self.replyLinks(ctx, url, saucenao=True, google=True, yandex=True, tineye=True, iqdb=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\requina\cogs\sauce - slash.py", line 101, in replyLinks
    await ctx.send(content=e, hidden=True)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord_slash\context.py", line 228, in send
    resp = await self._http.edit(base, self._token, files=files)
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Google Drive (frat8164@gmail.com)\programs\python\discord\.env\windows\lib\site-packages\discord\utils.py", line 328, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\khoi8\appdata\local\programs\python\python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AttributeError is not JSON serializable
07/30/2021 02:11:49 PM Received signal to terminate bot and event loop.
07/30/2021 02:11:49 PM Cleaning up tasks.
07/30/2021 02:11:49 PM Cleaning up after 2 tasks.
07/30/2021 02:11:49 PM All tasks finished cancelling.
07/30/2021 02:11:49 PM Closing the event loop.
07/30/2021 02:11:53 PM logging in using static token
07/30/2021 02:11:54 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:11:54 PM Shard ID None has connected to Gateway: ["gateway-prd-main-2s4s",{"micros":109174,"calls":["discord-sessions-green-prd-2-108",{"micros":108105,"calls":["start_session",{"micros":32835,"calls":["api-prd-main-hml1",{"micros":28819,"calls":["get_user",{"micros":3540},"add_authorized_ip",{"micros":1369},"get_guilds",{"micros":4072},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":19532,"calls":[]}]}]}] (Session ID: abbed2065d69c7876e34f1612ff8b5f9).
07/30/2021 02:11:56 PM Syncing commands...
07/30/2021 02:11:58 PM Syncing permissions...
07/30/2021 02:11:58 PM Deleting unused guild commands...
07/30/2021 02:11:58 PM Completed syncing all commands!
07/30/2021 02:14:13 PM Received signal to terminate bot and event loop.
07/30/2021 02:14:13 PM Cleaning up tasks.
07/30/2021 02:14:13 PM Cleaning up after 2 tasks.
07/30/2021 02:14:13 PM All tasks finished cancelling.
07/30/2021 02:14:13 PM Closing the event loop.
07/30/2021 02:14:17 PM logging in using static token
07/30/2021 02:14:18 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:14:18 PM Shard ID None has connected to Gateway: ["gateway-prd-main-r8wr",{"micros":81025,"calls":["discord-sessions-green-prd-2-118",{"micros":80285,"calls":["start_session",{"micros":42098,"calls":["api-prd-main-c2jx",{"micros":37469,"calls":["get_user",{"micros":3319},"add_authorized_ip",{"micros":1785},"get_guilds",{"micros":5666},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":35653,"calls":[]}]}]}] (Session ID: 740495061aee3fa0bff0c2d77643308c).
07/30/2021 02:14:20 PM Syncing commands...
07/30/2021 02:14:22 PM Syncing permissions...
07/30/2021 02:14:22 PM Deleting unused guild commands...
07/30/2021 02:14:22 PM Completed syncing all commands!
07/30/2021 02:14:43 PM Received signal to terminate bot and event loop.
07/30/2021 02:14:43 PM Cleaning up tasks.
07/30/2021 02:14:43 PM Cleaning up after 3 tasks.
07/30/2021 02:14:56 PM Closing the event loop.
07/30/2021 02:30:00 PM logging in using static token
07/30/2021 02:30:01 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:30:01 PM Shard ID None has connected to Gateway: ["gateway-prd-main-8g65",{"micros":73264,"calls":["discord-sessions-green-prd-2-7",{"micros":69349,"calls":["start_session",{"micros":30201,"calls":["api-prd-main-px0q",{"micros":27582,"calls":["get_user",{"micros":2480},"add_authorized_ip",{"micros":1844},"get_guilds",{"micros":4406},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":0,"calls":[]}]}]}] (Session ID: 6992a577e4b73ba8e413512d09ed6a86).
07/30/2021 02:30:03 PM Syncing commands...
07/30/2021 02:30:05 PM Syncing permissions...
07/30/2021 02:30:05 PM Deleting unused guild commands...
07/30/2021 02:30:05 PM Completed syncing all commands!
07/30/2021 02:31:15 PM Received signal to terminate bot and event loop.
07/30/2021 02:31:15 PM Cleaning up tasks.
07/30/2021 02:31:15 PM Cleaning up after 3 tasks.
07/30/2021 02:31:15 PM All tasks finished cancelling.
07/30/2021 02:31:15 PM Closing the event loop.
07/30/2021 02:31:19 PM logging in using static token
07/30/2021 02:31:20 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:31:20 PM Shard ID None has connected to Gateway: ["gateway-prd-main-8f6s",{"micros":117269,"calls":["discord-sessions-green-prd-2-133",{"micros":116144,"calls":["start_session",{"micros":41674,"calls":["api-prd-main-0vpr",{"micros":39479,"calls":["get_user",{"micros":7180},"add_authorized_ip",{"micros":1618},"get_guilds",{"micros":4491},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":26967,"calls":[]}]}]}] (Session ID: 47bad563f7e3a6177f9e1986cecaee55).
07/30/2021 02:31:22 PM Syncing commands...
07/30/2021 02:31:24 PM Syncing permissions...
07/30/2021 02:31:24 PM Deleting unused guild commands...
07/30/2021 02:31:24 PM Completed syncing all commands!
07/30/2021 02:34:24 PM Received signal to terminate bot and event loop.
07/30/2021 02:34:24 PM Cleaning up tasks.
07/30/2021 02:34:24 PM Cleaning up after 2 tasks.
07/30/2021 02:34:24 PM All tasks finished cancelling.
07/30/2021 02:34:24 PM Closing the event loop.
07/30/2021 02:34:28 PM logging in using static token
07/30/2021 02:34:28 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:34:29 PM Shard ID None has connected to Gateway: ["gateway-prd-main-zfxx",{"micros":87509,"calls":["discord-sessions-green-prd-2-153",{"micros":85155,"calls":["start_session",{"micros":31325,"calls":["api-prd-main-3dzb",{"micros":27949,"calls":["get_user",{"micros":2806},"add_authorized_ip",{"micros":1585},"get_guilds",{"micros":5070},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":32730,"calls":[]}]}]}] (Session ID: 14c632e946474dacee572c04d71759a7).
07/30/2021 02:34:31 PM Syncing commands...
07/30/2021 02:34:32 PM Syncing permissions...
07/30/2021 02:34:32 PM Deleting unused guild commands...
07/30/2021 02:34:33 PM Completed syncing all commands!
07/30/2021 02:39:45 PM Received signal to terminate bot and event loop.
07/30/2021 02:39:45 PM Cleaning up tasks.
07/30/2021 02:39:45 PM Cleaning up after 2 tasks.
07/30/2021 02:39:45 PM All tasks finished cancelling.
07/30/2021 02:39:45 PM Closing the event loop.
07/30/2021 02:39:48 PM logging in using static token
07/30/2021 02:39:49 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 02:39:50 PM Shard ID None has connected to Gateway: ["gateway-prd-main-t6x9",{"micros":115609,"calls":["discord-sessions-green-prd-2-163",{"micros":113574,"calls":["start_session",{"micros":90219,"calls":["api-prd-main-flxn",{"micros":50066,"calls":["get_user",{"micros":2496},"add_authorized_ip",{"micros":5894},"get_guilds",{"micros":4966},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 0821af10edb0665b813287c4f56c8453).
07/30/2021 02:39:52 PM Syncing commands...
07/30/2021 02:39:53 PM Syncing permissions...
07/30/2021 02:39:53 PM Deleting unused guild commands...
07/30/2021 02:39:54 PM Completed syncing all commands!
07/30/2021 03:01:01 PM Received signal to terminate bot and event loop.
07/30/2021 03:01:01 PM Cleaning up tasks.
07/30/2021 03:01:01 PM Cleaning up after 2 tasks.
07/30/2021 03:01:01 PM All tasks finished cancelling.
07/30/2021 03:01:01 PM Closing the event loop.
07/30/2021 03:01:05 PM logging in using static token
07/30/2021 03:01:06 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 03:01:06 PM Shard ID None has connected to Gateway: ["gateway-prd-main-6mgz",{"micros":47675,"calls":["discord-sessions-green-prd-2-96",{"micros":46974,"calls":["start_session",{"micros":38466,"calls":["api-prd-main-c2jx",{"micros":34422,"calls":["get_user",{"micros":3275},"add_authorized_ip",{"micros":2133},"get_guilds",{"micros":3999},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":0,"calls":[]}]}]}] (Session ID: 32a972702f803e2b010d45042781a7ec).
07/30/2021 03:01:08 PM Syncing commands...
07/30/2021 03:01:10 PM Syncing permissions...
07/30/2021 03:01:10 PM Deleting unused guild commands...
07/30/2021 03:01:10 PM Completed syncing all commands!
07/30/2021 03:02:37 PM Received signal to terminate bot and event loop.
07/30/2021 03:02:37 PM Cleaning up tasks.
07/30/2021 03:02:37 PM Cleaning up after 2 tasks.
07/30/2021 03:02:37 PM All tasks finished cancelling.
07/30/2021 03:02:37 PM Closing the event loop.
07/30/2021 03:02:41 PM logging in using static token
07/30/2021 03:02:42 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 03:02:42 PM Shard ID None has connected to Gateway: ["gateway-prd-main-nkgj",{"micros":64005,"calls":["discord-sessions-green-prd-2-172",{"micros":63228,"calls":["start_session",{"micros":37263,"calls":["api-prd-main-64vw",{"micros":34529,"calls":["get_user",{"micros":4877},"add_authorized_ip",{"micros":1909},"get_guilds",{"micros":2899},"coros_wait",{"micros":0}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: e7c9fcf624d60229628d4385f94fd4d8).
07/30/2021 03:02:45 PM Syncing commands...
07/30/2021 03:02:46 PM Syncing permissions...
07/30/2021 03:02:46 PM Deleting unused guild commands...
07/30/2021 03:02:47 PM Completed syncing all commands!
07/30/2021 03:03:15 PM Received signal to terminate bot and event loop.
07/30/2021 03:03:15 PM Cleaning up tasks.
07/30/2021 03:03:15 PM Cleaning up after 2 tasks.
07/30/2021 03:03:15 PM All tasks finished cancelling.
07/30/2021 03:03:15 PM Closing the event loop.
07/30/2021 03:03:19 PM logging in using static token
07/30/2021 03:03:20 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 03:03:20 PM Shard ID None has connected to Gateway: ["gateway-prd-main-bzkk",{"micros":153832,"calls":["discord-sessions-green-prd-2-160",{"micros":152566,"calls":["start_session",{"micros":115937,"calls":["api-prd-main-jvzh",{"micros":89446,"calls":["get_user",{"micros":9639},"add_authorized_ip",{"micros":7751},"get_guilds",{"micros":10821},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":18699,"calls":[]}]}]}] (Session ID: 7faad480ca3c6cd7cdaff81805f52fa2).
07/30/2021 03:03:22 PM Syncing commands...
07/30/2021 03:03:24 PM Syncing permissions...
07/30/2021 03:03:24 PM Deleting unused guild commands...
07/30/2021 03:03:24 PM Completed syncing all commands!
07/30/2021 03:06:05 PM Received signal to terminate bot and event loop.
07/30/2021 03:06:05 PM Cleaning up tasks.
07/30/2021 03:06:05 PM Cleaning up after 2 tasks.
07/30/2021 03:06:05 PM All tasks finished cancelling.
07/30/2021 03:06:05 PM Closing the event loop.
07/30/2021 03:06:09 PM logging in using static token
07/30/2021 03:06:10 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 03:06:10 PM Shard ID None has connected to Gateway: ["gateway-prd-main-z7w9",{"micros":92217,"calls":["discord-sessions-green-prd-2-78",{"micros":91514,"calls":["start_session",{"micros":82003,"calls":["api-prd-main-bvlb",{"micros":73779,"calls":["get_user",{"micros":5085},"add_authorized_ip",{"micros":11364},"get_guilds",{"micros":11319},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":5165,"calls":[]}]}]}] (Session ID: 92d1244fd2b4883ac6fe4f40f6af3660).
07/30/2021 03:06:13 PM Syncing commands...
07/30/2021 03:06:14 PM Syncing permissions...
07/30/2021 03:06:14 PM Deleting unused guild commands...
07/30/2021 03:06:14 PM Completed syncing all commands!
07/30/2021 03:10:01 PM Received signal to terminate bot and event loop.
07/30/2021 03:10:01 PM Cleaning up tasks.
07/30/2021 03:10:01 PM Cleaning up after 2 tasks.
07/30/2021 03:10:01 PM All tasks finished cancelling.
07/30/2021 03:10:01 PM Closing the event loop.
07/30/2021 03:13:23 PM logging in using static token
07/30/2021 03:13:24 PM Shard ID None has sent the IDENTIFY payload.
07/30/2021 03:13:24 PM Shard ID None has connected to Gateway: ["gateway-prd-main-rf43",{"micros":87903,"calls":["discord-sessions-green-prd-2-16",{"micros":86824,"calls":["start_session",{"micros":26275,"calls":["api-prd-main-nl4f",{"micros":23446,"calls":["get_user",{"micros":2490},"add_authorized_ip",{"micros":1536},"get_guilds",{"micros":3894},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":2,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 04aac1ed9f22f2db4689ee0be23e6829).
07/30/2021 03:13:26 PM Syncing commands...
07/30/2021 03:13:28 PM Syncing permissions...
07/30/2021 03:13:28 PM Deleting unused guild commands...
07/30/2021 03:13:28 PM Completed syncing all commands!
07/30/2021 04:12:23 PM Received signal to terminate bot and event loop.
07/30/2021 04:12:23 PM Cleaning up tasks.
07/30/2021 04:12:23 PM Cleaning up after 2 tasks.
07/30/2021 04:12:23 PM All tasks finished cancelling.
07/30/2021 04:12:23 PM Closing the event loop.
